spring:
  datasource:
    url: jdbc:h2:mem:modDb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    hu.diablo.sims4.mod.checker: TRACE
    